amcl:
  ros__parameters:
    use_sim_time: true

    # Frames
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"

    # Laser
    scan_topic: "/scan"          # matches your URDF plugin remap
    laser_min_range: 0.12
    laser_max_range: 12.0
    laser_model_type: "likelihood_field"

    # Particle filter
    min_particles: 500
    max_particles: 2000
    kld_err: 0.02
    kld_z: 0.99

    # Motion update thresholds
    update_min_d: 0.2
    update_min_a: 0.2

    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0

    # Odometry model
    odom_model_type: "diff"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2

    # Initial pose (can be overridden from RViz)
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0